# Generated by Django 3.2.6 on 2021-09-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='critic',
        ),
    ]
