# Generated by Django 3.2.6 on 2021-09-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_user_review_critic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='critic',
            new_name='user',
        ),
    ]
